version: "3.8"
services:
  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: qurious
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./tests/db/pg:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432