[package]
name = "qurious"
version = "0.1.0"
edition = "2021"




[dependencies]
sqlparser = { workspace = true }
parquet = { workspace = true }
arrow = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
tokio-stream = { workspace = true }
log = { workspace = true }
dashmap = "6.0.1"



[dev-dependencies]
arrow = { version = "52.0.0", features = ["prettyprint", "test_utils"] }